### ISSUE TITLE
Add implicit use rules

### ISSUE THREAD

**Issue by mterwoord** [JetBrains/resharper-devguide#44]
In my framework code, I use conventions for tying things together. However target items are not recognized as in use (so ReSharper flags them as dead code). Is there any way to make this happen?
Code sample:

        [AutoCommand]
        public ICommand MyCommand
        {
            get;
            private set;
        }

        private bool MyCommand_CanExecute(object param)
        {
            return true;
        }

        private void MyCommand_Execute(object param)
        {
            throw new NotImplementedException();
        }

The AutoCommand creates a Command, utilizing the 2 methods.

**Comment by citizenmatt** [comment]
You can mark the `AutoCommand` attribute with the `[MeansImplicitUse]` attribute, and it will mean that MyCommand is not marked as unused.

This repo is for topics related to the SDK documentation (e.g. where the docs aren't clear, or missing) rather than for the SDK itself - there is a better chance of things being answered in a more timely manner, by a wider community, by posting to StackOverflow with the resharper tag, or to the [Google group](https://groups.google.com/forum/#!forum/resharper-plugins)
